name = "portfolio-website"
compatibility_date = "2025-01-10"

[[d1_databases]]
binding = "portfolio_db"
database_name = "portfolio_db"
database_id = "fda1e00d-010a-4195-9ef8-aef64fa55070"

[[r2_buckets]]
binding = "portfolio_bucket"
bucket_name = "portfolio-image-storage"
